// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserAPI.Data;

#nullable disable

namespace UserAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240503160227_AddAllTables")]
    partial class AddAllTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserAPI.Models.LocalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("UserAPI.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kcal")
                        .HasColumnType("int");

                    b.Property<double>("Mass")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfProducts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("35ec7399-15aa-4b88-88e2-418fe38209dc"),
                            CreatedDate = new DateTime(2024, 5, 3, 19, 2, 26, 834, DateTimeKind.Local).AddTicks(9490),
                            Description = "Description",
                            Kcal = 10,
                            Mass = 0.0,
                            Name = "Курячі яйця",
                            NumberOfProducts = 0
                        },
                        new
                        {
                            Id = new Guid("0463431c-2f71-4ffb-a908-d6b5044b74e2"),
                            CreatedDate = new DateTime(2024, 5, 3, 19, 2, 26, 834, DateTimeKind.Local).AddTicks(9545),
                            Description = "Description",
                            Kcal = 15,
                            Mass = 0.0,
                            Name = "Картопля",
                            NumberOfProducts = 0
                        },
                        new
                        {
                            Id = new Guid("b1404200-c96e-4d77-9d8a-c5a3c6eb8063"),
                            CreatedDate = new DateTime(2024, 5, 3, 19, 2, 26, 834, DateTimeKind.Local).AddTicks(9576),
                            Description = "Description",
                            Kcal = 25,
                            Mass = 0.0,
                            Name = "Цибуля",
                            NumberOfProducts = 0
                        });
                });

            modelBuilder.Entity("UserAPI.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9c679aa-cb3d-44ce-bb7a-3c88abbef149"),
                            Description = "Description",
                            Name = "Яєчня",
                            ProductIds = "[\"35ec7399-15aa-4b88-88e2-418fe38209dc\"]"
                        },
                        new
                        {
                            Id = new Guid("75b974d1-e2be-4714-b9c2-8e5fd3dd1fc9"),
                            Description = "Description",
                            Name = "Картопля з цибулею",
                            ProductIds = "[\"0463431c-2f71-4ffb-a908-d6b5044b74e2\",\"b1404200-c96e-4d77-9d8a-c5a3c6eb8063\"]"
                        },
                        new
                        {
                            Id = new Guid("0e9d3a5c-71bc-4847-bca7-ab0b1f9a0b85"),
                            Description = "Description",
                            Name = "Картопля з яйцем та цибулею",
                            ProductIds = "[\"35ec7399-15aa-4b88-88e2-418fe38209dc\",\"0463431c-2f71-4ffb-a908-d6b5044b74e2\",\"b1404200-c96e-4d77-9d8a-c5a3c6eb8063\"]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
