// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAPI.Data;

#nullable disable

namespace ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240503160140_AddAllTables")]
    partial class AddAllTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductAPI.Models.LocalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("ProductAPI.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kcal")
                        .HasColumnType("int");

                    b.Property<double>("Mass")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfProducts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9438ac9d-603c-4ed1-a1dd-cdb1bfc3ea85"),
                            CreatedDate = new DateTime(2024, 5, 3, 19, 1, 39, 786, DateTimeKind.Local).AddTicks(5573),
                            Description = "Description",
                            Kcal = 10,
                            Mass = 0.0,
                            Name = "Курячі яйця",
                            NumberOfProducts = 0
                        },
                        new
                        {
                            Id = new Guid("636c5598-0b67-4843-aa95-65762c683292"),
                            CreatedDate = new DateTime(2024, 5, 3, 19, 1, 39, 786, DateTimeKind.Local).AddTicks(5667),
                            Description = "Description",
                            Kcal = 15,
                            Mass = 0.0,
                            Name = "Картопля",
                            NumberOfProducts = 0
                        },
                        new
                        {
                            Id = new Guid("00f68eef-a3b1-4258-9f0c-984af408d10f"),
                            CreatedDate = new DateTime(2024, 5, 3, 19, 1, 39, 786, DateTimeKind.Local).AddTicks(5671),
                            Description = "Description",
                            Kcal = 25,
                            Mass = 0.0,
                            Name = "Цибуля",
                            NumberOfProducts = 0
                        });
                });

            modelBuilder.Entity("ProductAPI.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39e17efa-0ea8-4338-a2a7-bd81c719d839"),
                            Description = "Description",
                            Name = "Яєчня",
                            ProductIds = "[\"9438ac9d-603c-4ed1-a1dd-cdb1bfc3ea85\"]"
                        },
                        new
                        {
                            Id = new Guid("4051a325-80f5-4999-ae7b-c7f1c3f9d84b"),
                            Description = "Description",
                            Name = "Картопля з цибулею",
                            ProductIds = "[\"636c5598-0b67-4843-aa95-65762c683292\",\"00f68eef-a3b1-4258-9f0c-984af408d10f\"]"
                        },
                        new
                        {
                            Id = new Guid("0f5b1d4c-6a7d-42a4-b0df-710754183b5e"),
                            Description = "Description",
                            Name = "Картопля з яйцем та цибулею",
                            ProductIds = "[\"9438ac9d-603c-4ed1-a1dd-cdb1bfc3ea85\",\"636c5598-0b67-4843-aa95-65762c683292\",\"00f68eef-a3b1-4258-9f0c-984af408d10f\"]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
