// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAPI.Data;

#nullable disable

namespace ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductAPI.Models.LocalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("ProductAPI.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kcal")
                        .HasColumnType("int");

                    b.Property<double>("Mass")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfProducts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b89caa2-43d1-4e2f-abb3-4b180151bbee"),
                            CreatedDate = new DateTime(2024, 5, 3, 19, 6, 44, 438, DateTimeKind.Local).AddTicks(3715),
                            Description = "Description",
                            Kcal = 10,
                            Mass = 0.0,
                            Name = "Курячі яйця",
                            NumberOfProducts = 0
                        },
                        new
                        {
                            Id = new Guid("da182d0e-3b4e-459f-888f-89f91097a4cd"),
                            CreatedDate = new DateTime(2024, 5, 3, 19, 6, 44, 438, DateTimeKind.Local).AddTicks(3779),
                            Description = "Description",
                            Kcal = 15,
                            Mass = 0.0,
                            Name = "Картопля",
                            NumberOfProducts = 0
                        },
                        new
                        {
                            Id = new Guid("dd15bc8c-9886-4895-badd-6a70f999ca91"),
                            CreatedDate = new DateTime(2024, 5, 3, 19, 6, 44, 438, DateTimeKind.Local).AddTicks(3781),
                            Description = "Description",
                            Kcal = 25,
                            Mass = 0.0,
                            Name = "Цибуля",
                            NumberOfProducts = 0
                        });
                });

            modelBuilder.Entity("ProductAPI.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8dd58fbd-267e-4030-840b-c9ed45e78fa6"),
                            Description = "Description",
                            Name = "Яєчня",
                            ProductIds = "[\"7b89caa2-43d1-4e2f-abb3-4b180151bbee\"]"
                        },
                        new
                        {
                            Id = new Guid("7681376a-fb2f-4c35-b292-f738e3929cb4"),
                            Description = "Description",
                            Name = "Картопля з цибулею",
                            ProductIds = "[\"da182d0e-3b4e-459f-888f-89f91097a4cd\",\"dd15bc8c-9886-4895-badd-6a70f999ca91\"]"
                        },
                        new
                        {
                            Id = new Guid("9726212e-3182-456a-b97c-0eb7ff0407c3"),
                            Description = "Description",
                            Name = "Картопля з яйцем та цибулею",
                            ProductIds = "[\"7b89caa2-43d1-4e2f-abb3-4b180151bbee\",\"da182d0e-3b4e-459f-888f-89f91097a4cd\",\"dd15bc8c-9886-4895-badd-6a70f999ca91\"]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
